<?php
/**
 * Created by PhpStorm.
 * User: AAA
 * Date: 2019/5/8
 * Time: 23:37
 */

namespace app\api\service;

require_once __DIR__."/../../../extend/WxPay/WxPay.Api.php";

class WxNotify extends \WxPayNotify
{
    public function NotifyProcess($objData, $config, &$msg)
    {
        return parent::NotifyProcess($objData, $config, $msg); // TODO: Change the autogenerated stub
    }
}
